version: '3.8'

services:
  jekyll:
    build: .
    container_name: truckulent
    platform: linux/arm64
    volumes:
      - .:/srv/jekyll
      - bundle_cache:/usr/local/bundle
    ports:
      - "4000:4000"
      - 35729:35729
    environment:
      - JEKYLL_ENV=development
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
      - GOOGLE_GEOCODING_API_KEY=${GOOGLE_GEOCODING_API_KEY}
    env_file:
      - .env
    entrypoint: ["sh", "./start.sh"]

volumes:
  bundle_cache:
