name: Build and Deploy Jekyll Site

on:
  schedule:
    # Run every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Debug repository info
      run: |
        echo "Repository: ${{ github.repository }}"
        echo "Ref: ${{ github.ref }}"
        echo "Actor: ${{ github.actor }}"
        echo "Event: ${{ github.event_name }}"
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Docker image
      run: |
        docker build -t truckulent .
        
    - name: Create data directory
      run: |
        mkdir -p _data
        mkdir -p _site
        
    - name: Build Jekyll site with data fetching
      run: |
        docker run --rm --entrypoint="" \
          -e JEKYLL_ENV=production \
          -e SUPABASE_URL=${{ secrets.SUPABASE_URL }} \
          -e SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }} \
          -e GOOGLE_MAPS_API_KEY=${{ secrets.GOOGLE_MAPS_API_KEY }} \
          -e GOOGLE_GEOCODING_API_KEY=${{ secrets.GOOGLE_GEOCODING_API_KEY }} \
          -v ${{ github.workspace }}:/srv/jekyll \
          -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          truckulent \
          bundle exec jekyll build
          
    - name: Verify build output
      run: |
        echo "Build output contents:"
        ls -la _site/
        echo "Index file exists:"
        ls -la _site/index.html
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
        # Optional: Add your custom domain here
        # cname: your-domain.com
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
