name: Build and Deploy Jekyll Site

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  # schedule:
  #   # Run every 6 hours
  #   - cron: '0 */6 * * *'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Debug repository info
      run: |
        echo "Repository: ${{ github.repository }}"
        echo "Ref: ${{ github.ref }}"
        echo "Actor: ${{ github.actor }}"
        echo "Event: ${{ github.event_name }}"
      
    - name: Create data directory
      run: |
        mkdir -p _data
        mkdir -p docs
        
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: false
        
    - name: Install dependencies
      run: |
        bundle lock --add-platform x86_64-linux
        bundle install
        
    - name: Fetch data
      run: |
        ruby scripts/fetch-data.rb
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL || 'https://placeholder.supabase.co' }}
        SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY || 'placeholder-key' }}
        GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY || 'placeholder-key' }}
        GOOGLE_GEOCODING_API_KEY: ${{ secrets.GOOGLE_GEOCODING_API_KEY || 'placeholder-key' }}
        
    - name: Build Jekyll site
      run: |
        bundle exec jekyll build --destination docs
          
    - name: Verify build output
      run: |
        echo "Build output contents:"
        ls -la docs/
        echo "Index file exists:"
        ls -la docs/index.html
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
